EmployeeProject.UI/Controllers/EmployeeController.cs
using EmployeeProject.Application.DTOs.Admin;
using EmployeeProject.Application.DTOs.Employee;
using EmployeeProject.Application.Interfaces;
using EmployeeProject.Application.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeProject.UI.Controllers
{

    [Authorize(Policy = "RequireEmployeeRole")]
    public class EmployeeController : BaseController<EmployeeController>
    {
        private readonly IAdminServices adminServices;
        private readonly ILogger<AdminController> logger;

        public EmployeeController(IAdminServices adminServices, ILogger<AdminController> logger)
        {
            this.adminServices = adminServices;
            this.logger = logger;   
        }

        public IActionResult Index(string success)
        {
            if (success != null)
            {
                TempData["Login"] = success.ToString();
                var model = new IndexDTO();
                return View(model);
            }
            else
            {
                var model = new IndexDTO();
                return View(model);
            }

         
        }

        public IActionResult DataSheet()
        {
            return View();
        }

        public IActionResult Holidays()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> UpdateProfile(IFormFile image)
        {
            try
            {
                var result = await adminServices.UpdateProfile(image);
                if (result)
                {
                    TempData["ProfileUpdated"] = "Profile Updated Successfully!";
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "Error occured while processing, in ");
                return Json(new { message = "failed" });
            }
        }

    }
}

EmployeeProject.UI/Controllers/ExternalController.cs
using EmployeeProject.Core.Entities.User;
using ExternalLogin.Extensions;
using ExternalLogin.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System.Net.Http;

namespace EmployeeProject.UI.Controllers
{
    public class ExternalController : BaseController<ExternalController>
    {
        private readonly IExternalLoginService externalLoginService;
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public ExternalController(
            IExternalLoginService externalLoginService,
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager)
        {
            this.externalLoginService = externalLoginService;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> Login(string token) // make sure to add the parameter in the endpoint
        {
            try
            {
                var ipaddress = HttpContext.IpAddress();
                var usercode = string.Empty;

                if (externalLoginService.TryValidateToken(token, ipaddress, out usercode))
                    return await AuthenticateUser(usercode); // if validated, this is where you setup the user session 

                return RedirectToAction("Index", "Employee");
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error in Login action of ExternalController");
                return RedirectToAction("Index", "Employee");
            }
        }

        public IActionResult Logout()
        {
            try
            {
                signInManager.SignOutAsync();
                HttpContext.Session.Remove("UsersId");

                return Redirect(externalLoginService.PortalUrl);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error in Logout action of ExternalController");
                return RedirectToAction("Index", "Employee");
            }
        }

        private async Task<IActionResult> AuthenticateUser(string usercode)
        {
            try
            {
                var user = await userManager.FindByEmailAsync(usercode + "@princeretail.com");

                if (user != null)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);

                    var userRoles = await userManager.GetRolesAsync(user);
                    var userRole = userRoles.FirstOrDefault();

                    HttpContext.Session.SetString("UsersId", user.Id);

                    if (userRole == "Manager")
                    {
                        return RedirectToAction("Index", "Admin", new { success = "Login SuccessFully!" });
                    }
                    else if (userRole == "Project_Manager")
                    {
                        return RedirectToAction("Index", "Admin", new { success = "Login SuccessFully!" });
                    }
                    else if (userRole == "Employee")
                    {
                        return RedirectToAction("Index", "Employee", new { success = "Login SuccessFully!" });
                    }
                    else if (userRole == "Admin")
                    {
                        return RedirectToAction("Index", "Admin", new { success = "Login SuccessFully!" });
                    }

                }

                return Redirect(externalLoginService.PortalUrl);
            }
            catch (Exception ex)
            {
                Log.Error(ex, "Error in AuthenticateUser action of ExternalController");
                return RedirectToAction("Index", "Employee");
            }
        }
    }
}

EmployeeProject.UI/Views/Shared/_EmployeeLayout.cshtml
@using EmployeeProject.Core.Entities.User
@using Microsoft.AspNetCore.Identity;
@using Microsoft.EntityFrameworkCore;
@inject SignInManager<AppUser> signManager;
@inject UserManager<AppUser> userManager;
@{
    var user = await userManager.GetUserAsync(User);

    var currentUser = await userManager.Users
    .Include(u => u.Section)
    .FirstOrDefaultAsync(u => u.Id == user.Id);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/employee/index.css" />
    <link rel="stylesheet" href="~/css/employee/dataSheet.css" />
    <link rel="stylesheet" href="~/css/employee/holiday.css" />

</head>
<body>
    <div class="employeeBody">
        <div class="employeeNavbar"> 
            <div class="employeeNavbarDiv1">
                <a class="navbarHome" asp-controller="Employee" asp-action="Index"><i class="fa fa-home" aria-hidden="true"></i>Home</a>
                <a class="navbarDataSheet" asp-controller="Employee" asp-action="DataSheet"><i class="fa fa-file-text"  aria-hidden="true"></i>DataSheet</a>
                <a class="navbarHoliday" asp-controller="Employee" asp-action="Holidays"><i class="fa-solid fa-umbrella-beach"></i>Holidays</a>
            </div>
            <div class="employeeNavbarDiv2">
                <div class="btn-group">
                    <button type="button" class="btn employeeDropdown dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @currentUser.FullName
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button" data-bs-toggle="modal" data-bs-target="#profileModal1">View Profile</button>
                        <button class="dropdown-item" type="button" data-bs-toggle="modal" data-bs-target="#logoutModalEmployee">Logout</button>
                    </div>
                </div>
            </div>
        </div>
 
            @RenderBody()

    </div>


                    @*LOGOUT MODAL*@
    <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" id="logoutModalEmployee" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="height:50vh;">
            <div class="modal-content" style="height: 240px;">
                <div class="modal-body logoutModalBody">
                    <div class="logoutModalBody1">
                        <h3>Are you sure you want to logout?</h3>
                    </div>
                    <div class="logoutModalBody2">
                        <a class="btn btn-danger logoutYes" asp-action="Logout" asp-controller="External">Yes</a>
                        <button type="button" class="close btn btn-success logoutNo" data-bs-dismiss="modal" aria-label="Close">
                            No
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*PROFILE MODAL*@
    <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" id="profileModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="height:50vh;">

            <div class="modal-content" style="height: 450px;">

                <div class="modal-header profileHeader">
                    <div class="profileHeaderDiv1">
                        <i class="fa fa-times closeProfileModal" aria-hidden="true" data-bs-dismiss="modal" aria-label="Close"></i>
                    </div>

                    <div class="profileHeaderDiv2">

                        @if (currentUser.profileString != null)
                        {
                            <img src="~/profile/@currentUser.profileString" class="userProfilePic" />
                        }
                        else
                        {
                            <img src="~/profile/default.jpg" class="userProfilePic" />
                        }

                    </div>

                </div>

                <div class="modal-body profileModalBody">

                    <div class="profileModalBodyDiv1">
                        <h4 style="text-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);">@currentUser.FullName</h4>
                        <h5 style="font-weight:500;">

                            @if (currentUser.position != null)
                            {
                                @currentUser.position
                            }
                            else
                            {
                                <span>No Position Yet</span>
                            }

                        </h5>
                    </div>
                    <div class="profileModalBodyDiv2">

                        <div class="profileModalBodyDiv2Inner1">

                            <div class="profileModalBodyDiv2Inner1Div1">
                                <i class="fa fa-envelope emailProfile" aria-hidden="true"></i>
                            </div>

                            <div class="profileModalBodyDiv2Inner1Div2">

                                <span style="margin-right:15%;">
                                    @if (currentUser.Email != null)
                                    {
                                        @currentUser.Email
                                    }
                                    else
                                    {
                                        <span>No Email Yet</span>
                                    }
                                </span>

                            </div>

                        </div>



                        <div class="profileModalBodyDiv2Inner2">

                            <div class="profileModalBodyDiv2Inner2Div1">
                                <i class="fa fa-sitemap phoneProfile" aria-hidden="true"></i>
                            </div>
                            <div class="profileModalBodyDiv2Inner2Div2">
                                <span style="margin-right:25%;">

                                    @if (currentUser.Section?.SectionName != null)
                                    {
                                        @currentUser.Section.SectionName
                                    }
                                    else
                                    {
                                        <span>No Section Yet</span>
                                    }

                                </span>
                            </div>

                        </div>


                    </div>
                    <div class="profileModalBodyDiv3">
                        <button class="profileEditBtn" data-bs-toggle="modal" data-bs-target="#profileModalEdit">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                            Edit
                        </button>
                    </div>

                </div>

            </div>
        </div>
    </div>




    @*EDIT PROFILE MODAL*@
    <form method="post" enctype="multipart/form-data" asp-action="UpdateProfile" asp-controller="Employee">
        <div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" id="profileModalEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document" style="height:50vh;">

                <div class="modal-content profileEditModalContent" style="height: 450px;">

                    <div class="modal-header profileHeader">
                        <div class="profileHeaderDiv1">
                            <i class="fa fa-times closeProfileModal" aria-hidden="true" data-bs-dismiss="modal" aria-label="Close"></i>
                        </div>

                        <div class="profileHeaderDiv2">

                            @if (currentUser.profileString != null)
                            {
                                <img src="~/profile/@currentUser.profileString" class="userProfilePic" />
                            }
                            else
                            {
                                <img src="~/profile/default.jpg" class="userProfilePic" />
                            }

                            <label for="profileEditButton"><i class="fa fa-plus" aria-hidden="true"></i></label>
                            <input type="file" id="profileEditButton" name="image" accept=".png, .jpg, .jpeg, .jfif" />
                        </div>

                    </div>

                    <div class="modal-body profileModalBody">

                        <div class="profileModalBodyDiv1">
                            <h4 style="text-shadow: 0 4px 4px rgba(0, 0, 0, 0.25);">@currentUser.FullName</h4>
                            <h5 style="font-weight:500;">

                                @if (currentUser.position != null)
                                {
                                    @currentUser.position
                                }
                                else
                                {
                                    <span>No Position Yet</span>
                                }

                            </h5>
                        </div>
                        <div class="profileModalBodyDiv2">

                            <div class="profileModalBodyDiv2Inner1">

                                <div class="profileModalBodyDiv2Inner1Div1">
                                    <i class="fa fa-envelope emailProfile" aria-hidden="true"></i>
                                </div>

                                <div class="profileModalBodyDiv2Inner1Div2">

                                    <span style="margin-right:15%;">
                                        @if (currentUser.Email != null)
                                        {
                                            @currentUser.Email
                                        }
                                        else
                                        {
                                            <span>No Email Yet</span>
                                        }
                                    </span>

                                </div>

                            </div>

                            <div class="profileModalBodyDiv2Inner2">

                                <div class="profileModalBodyDiv2Inner2Div1">
                                    <i class="fa fa-sitemap phoneProfile" aria-hidden="true"></i>
                                </div>
                                <div class="profileModalBodyDiv2Inner2Div2">
                                    <span style="margin-right:15%;">

                                        @if (currentUser.Section?.SectionName != null)
                                        {
                                            @currentUser.Section.SectionName
                                        }
                                        else
                                        {
                                            <span>No Section Yet</span>
                                        }

                                    </span>
                                </div>

                            </div>


                        </div>
                        <div class="profileModalBodyDiv3">
                            <button class="profileEditBtn" type="submit">
                                <i class="fa fa-check" aria-hidden="true"></i>
                                Save
                            </button>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </form>




</body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
      <script src="~/js/employee.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

<script src="~/js/signalr.js"></script>
<script src="~/js/signalr.min.js"></script>
<script>


    // const fileInput = document.getElementById('file-input');

    // fileInput.addEventListener('change', function () {
    //     const file = this.files[0];
    //     const allowedTypes = ['image/png', 'image/jpeg', 'image/jpg', 'image/jfif'];

    //     if (!allowedTypes.includes(file.type)) {
    //         alert('Please select a PNG or JPEG image file.');
    //         this.value = ''; 
    //     }
    // });

</script>
</html>

EmployeeProject.UI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/home/home.css" />

</head>
<body>

        @RenderBody()

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

</body>
</html>